### ISSUE TITLE
Invalid Wincmd

### ISSUE THREAD

**Issue by starcraftman** [Konfekt/FastFold#11]
Hi, I apparently haven't updated this plugin often and upon updating I noticed a bug. The error text is here:

```
Error detected while processing function <SNR>45_LeaveAllWinOfBuf..<SNR>45_WinDo:
line    4:
".vimrc" 1332L, 38289C written
Error detected while processing function <SNR>45_EnterAllWinOfBuf..<SNR>45_WinDo:
line    4:
E16: Invalid range: 0wincmd w
```

It appears that a merge last year 7b78c6a added a call to the WinDo function for winnr('%'), this returns 0 when you've only focused/had one buffer loaded. It then issues an invalid command twice. I suppose it could be easily fixed with a ternary that checked for zero and put 1 in if it is 0.

`  let curaltwin = winnr('#') ? winnr('#') : 1  `

I'll go make a PR to fix it.

**Comment by Konfekt** [comment]
Ok. I look into it. However, tell me which Vim version you are using (see https://groups.google.com/forum/#!topic/vim_dev/LLTw8JV6wKg).

**Comment by starcraftman** [comment]
@Konfekt Ah didn't know they are patching wincmd recently. I'm using vim 7.4.567. I compile manually every so often, perhaps thats the recent change that broke this.

**Comment by Konfekt** [comment]
@wilywampa @blueyed seems latest vim patches broke your restore of the alternate current window. I just use the proposed workaround by starcraftman.

**Comment by Konfekt** [comment]
Thanks. I use your workaround and add a remark that this is to work around a Vim bug.

**Comment by starcraftman** [comment]
@Konfekt Glad to help, thanks for speedy response.
