### ISSUE TITLE
Function missing for save error.

### ISSUE THREAD

**Issue by lethjakman** [Konfekt/FastFold#12]
Hey, every time I save I'm getting the errors:

```error
Error detected while processing function <SNR>65_LeaveAllWinOfBuf..<SNR>65_WinDo:
line    4:
"blah.rb" [New] 0L, 0C written
Error detected while processing function <SNR>65_EnterAllWinOfBuf..<SNR>65_WinDo:
line    4:
E16: Invalid range: 0wincmd w
Press ENTER or type command to continue
```
This worked great on my Mac, but starting today on ubuntu I started getting this error.

**Comment by Konfekt** [comment]
Well this is a new Vim bug and should have been fixed yesterday. See https://github.com/Konfekt/FastFold/issues/11
