### ISSUE TITLE
w:lastfdm variable not updated when opening existing buffer.

### ISSUE THREAD

**Issue by Parakleta** [Konfekt/FastFold#15]
If I have two different buffers open in splits with different foldmethods, then if I edit the first buffer (e.g. with `:edit #`) in the second split window the value of `w:lastfdm` is preserve in that window rather than being set to the foldmethod of the buffer (or erased).

**Comment by Konfekt** [comment]
Well, I think the way it is, it is correct because `fdm` is by Vim's definition window (and not buffer) local. The `b:lastfdm` appearing in `plugin/fastfold.vim` is only a crutch to guess the window's `fdm` in case it is yet unset.

**Comment by Parakleta** [comment]
I did some further testing and you are correct that this is the default behaviour of Vim.  Is there any chance that a feature could be added to your plugin to allow overriding of this behaviour.  The existing behaviour is problematic for me because using a mixture of syntax/expr folding (code and documentation) is messing up my view files.

**Comment by Konfekt** [comment]
Well, I thought about it a bit more and on the other hand there's a default foldmethod for each Filetype, which is a buffer event. 

So I made a commit that sets the fold method to that of the last acccessed window by default when displaying a buffer anew. 

I also made a lot of other changes, so I'd be glad to know How everything worked out for you.

**Comment by Parakleta** [comment]
Seems all good, I haven't checked corner cases but everything appears to work for my normal use.
