### ISSUE TITLE
problems with folding javascript files

### ISSUE THREAD

**Issue by szymonkaliski** [Konfekt/FastFold#17]
I have pangloss/vim-javascript for JS folding and I'm having troubles making it work with FastFold.

When I open JS file with both plugins activated and try to do anything with folds I get "E490: No fold found", only when manually setting "set foldmethod=synax" I get working folding. If I fold something and check with "set foldmethod" I get back "manual" so it looks like FastFold is working.

In my vimrc I have:
```
set foldenable                                                                                                                                       
set foldmethod=syntax                                                                                                                                
set foldlevelstart=99                                                                                                                                
set foldcolumn=0
```

**Comment by Konfekt** [comment]
Could you hit `zuz` (or `:FastFoldUpdate!`) and see what that gives?

 If you use FastFold's latest instalment, the ftplugin settings should update the foldmethod uses by FastFold. Does adding `setlocal foldmethod=syntax` to `~/after/ftplugin/javascript.vim` change anything?

**Comment by szymonkaliski** [comment]
`zuz` returns this: `'manual' folds already continuously updated`, folding doesn't work after either (same with `:FastFoldUpdate!`)

I don't really use ftplugins (I like to have everything in one file) but did this (should have the same effect right? I've been using vim for a while now but still feel like a beginner sometimes) :)

```viml
augroup ft_settings
  au!
  au FileType javascript setlocal foldmethod=syntax
augroup END
```

Unfortunately this doesn't help.

Yes, I have most recent FastFold version.

**Comment by Konfekt** [comment]
Yep, the autocmd is just as fine as a ftplugin setting. 

Strange. If you enter :set fdm=syntax,  then hitting zuz should show that this fold method is used and everything work as expected. Is that at least the case?

**Comment by Konfekt** [comment]
Hmm.. Perhaps I think I was mistaken. Try  the after ftplugin folder solution as well. The load order may be different from your autocmd.

**Comment by szymonkaliski** [comment]
>Strange. If you enter :set fdm=syntax, then hitting zuz should show that this fold method is used and everything work as expected. Is that at least the case?

Yes, everything works fine then!

>Hmm.. Perhaps I think I was mistaken. Try the after ftplugin folder solution as well. The load order may be different from your autocmd.

Tried, sadly no difference.

Strange thing is — it used to work, I'm just not really sure when exactly, but some previous version of FastFold was working fine, I've been keeping my plugins updated and don't know when it broke down really...

**Comment by Konfekt** [comment]
Ok,  is it the Version before the last commit, that's 

https://github.com/Konfekt/FastFold/commit/324ba282bf836fffe937f89e12b5268b9260fdb0

Could you check that? If not, perhaps 

https://github.com/Konfekt/FastFold/commit/324ba282bf836fffe937f89e12b5268b9260fdb0

changes anything ? 

It surprises that the js Filetype autocmd doesn't change anything, because just the latest commit adds a trigger for such events.

**Comment by Konfekt** [comment]
Also good to know: Does commenting out either of the autocmds at https://github.com/Konfekt/FastFold/blob/master/plugin/fastfold.vim#L160 or the line below change anything ? Perhaps you could try that first

**Comment by Konfekt** [comment]
Another problem could be: Do you use a plugin like `vim-stay` that makes the current fold method persistent by view files? Perhaps the file that you are checking has a view file that erroneously saves `fdm=manual`.

**Comment by szymonkaliski** [comment]
>Also good to know: Does commenting out either of the autocmds at https://github.com/Konfekt/FastFold/blob/master/plugin/fastfold.vim#L163 or the line below change anything ? Perhaps you could try that first

Yes! Commenting this line fixes everything. Folds work and `zuz` gives me `updated 'syntax' folds`.

I'm not using `vim-stay` or anything like this, I'm just opening file with `vim file.js`.

**Comment by Konfekt** [comment]
Thank you Szymon! Should work now. The `FileType` autocmd came before that on `BufWinEnter` which overrode `lastfdm` by `manual`. Please give it a spin and feel free to close.

**Comment by szymonkaliski** [comment]
Thank you! Everything is working great now :)
