### ISSUE TITLE
New files are not folded by default

### ISSUE THREAD

**Issue by eapache** [Konfekt/FastFold#20]
I was using 07c93f7 and noticed this issue after updating to the latest master. A quick bisect showed it was introduced in 7dffcd1.

When I load a file (with e.g. `vim foo.rb`) no folds are created by default now, and I have to manually run `zuz` or `:FastFoldUpdate` to create all the folds.

**Comment by Konfekt** [comment]
Thanks for reporting! I was using `vim-stay` and thus didn't notice. Somehow the `WinDo` cycle is critical for folds to update, don't ask me but Vim why.

Can you confirm it's fixed?

If you know how to suppress the `fdm=...` output, I'd be happy to know.

**Comment by eapache** [comment]
Yes, it seems to be fixed now, thanks! Not sure what you mean by the `fdm=` output, I don't see any output coming from FastFold on my machine.

**Comment by Konfekt** [comment]
Ok, here there's always a line fold method = manual when command line vim opens a file
