### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gi1242** [Konfekt/FastFold#24]
Recently I've found that after an hour or two of editing the same file (latex) the amount of memory occupied by Vim seems to grow (and eventually I have to quit it since it brings my system to a grinding halt).

Has anyone experienced anything similar?

**Comment by Konfekt** [comment]
Could you isolate FastFold as the cause of the problem? As it stands, the issue is vague and no hint that this is the case.

**Comment by gi1242** [comment]
I couldn't isolate the problem. I tried. It happens every couple of
days on long files... and I can't seem to find the trick to reproducing
it consistently enough to try and isolate the problem.

-- 
A man's home is his castle, in a manor of speaking.

**Comment by Konfekt** [comment]
I hope you're reluctant to run Vim without FastFold for a week or so to see if it is still occurs? FastFold doesn't do much but sending `set fdm=syntax/expr` and `set fdm=manual` when called for.

**Comment by gi1242** [comment]
Ha. Without fast fold, I have to disable syntax folding otherwise Vim is
unusable on anything I work on. When I disable syntax folding too I get
no problems...

It might very well be something else. My original thought was a memory
leak in vim itself when changing the fold method so often... but I might
be completely wrong.

GI

-- 
An Apple a day, keeps Windows away.

**Comment by Konfekt** [comment]
How about a macro `qq`, then `:set fdm=syntax<cr>:set fdm=manual<cr>` and finally `999@q`?

**Comment by Konfekt** [comment]
Then compare the memory consumptions by `Vim` in some process manager.

**Comment by gi1242** [comment]
OK, just tired this. Tried a whole bunch of other macro combinations
too. It ran out of memory once. I can't seem to reproduce it
consistently though. Will try more.

-- 
TEN SURE SIGNS THE RECESSION HAS HIT REALLY HARD
6. Angelina Jolie adopted a child from America.

**Comment by Konfekt** [comment]
Did some pattern evolve? In any case that is in all likelihood an upstream issue.

**Comment by gi1242** [comment]
On Thu, Nov 19, 2015 at 11:42:55PM -0800, Konfekt wrote:

> Did some pattern evolve? In any case that is in all likelihood an
> upstream issue. 

Yeah, it's probably an issue somewhere else! Problem still recurs for me
and I still can't reproduce it :).

Just close it. If I figure it out I'll reopen (if it's FastFold) or post
to upstream.

GI

-- 
TWELVE REASONS WHY GOD NEVER RECEIVED TENURE
5. He never applied to the Ethics Board for permission to use human
subjects.
