### ISSUE TITLE
Buffer Switching Slow

### ISSUE THREAD

**Issue by yamsu** [Konfekt/FastFold#28]
Hi,

The FastFold plugin has really helped to speed up scrolling in my vim configuration. However, I have been experiencing lag >1s when switching between large buffers (i.e. using bn//bp). I did a profile of the function running during this switch and found that the following command takes up the bulk of the processing:
silent! execute 'keepjumps noautocmd windo ' . a:command

Profile extract below:
FUNCTION  <SNR>82_WinDo()
Called 4 times
Total time:   1.059916
 Self time:   1.059512

count  total (s)   self (s)
                              " Work around Vim bug.
                              " See https://groups.google.com/forum/#!topic/vim_dev/LLTw8JV6wKg
    4              0.000042   let curaltwin = winnr('#') ? winnr('#') : 1
    4              0.000020   let currwin=winnr()
                              " avoid errors in CmdWin
    4              0.000043   if exists('*getcmdwintype') && getcmdwintype() != ''
                                return
                              endif
    4   1.059630   1.059226   silent! execute 'keepjumps noautocmd windo ' . a:command
    4              0.000088   silent! execute curaltwin . 'wincmd w'
    4              0.000035   silent! execute currwin . 'wincmd w'

Profiling procedure
As described by ZyX in
http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow

What does this command do and can it be modified to reduce this delay? I have commented it out and there is no lag between buffer switching. Please note buffer size of over 1500 lines usually show the lag.

Profile log attached
[vim-profile.txt](https://github.com/Konfekt/FastFold/files/72524/vim-profile.txt)

**Comment by Konfekt** [comment]
This command updates the folds. The same as hitting zuz which therefore should also consume a second. Now that it takes up that much time is also happening over here, for larger TeX files with concealing enabled. 

So folds should not be updated anymore on entering a buffer once it is loaded? Perhaps reasonable.

**Comment by Konfekt** [comment]
I pushed a commit that should no longer update folds on entering a buffer (but only the foldmethod). Could you check if it fastens up buffer switching?

**Comment by yamsu** [comment]
Thats has fixed the problem thanks

**Comment by Konfekt** [comment]
Thanks for reporting!

**Comment by vanabel** [comment]
Did this commit only work for the branch `vimenter` rather than `master`? Since I face the same problem when switch by `tabp/tabn`.

**Comment by Konfekt** [comment]
No, for both. But tabp/n is a different story. There's an autocmd to update folds on tabenter, as a tab can contain a whole bunch of open buffers.

**Comment by rcaputo** [comment]
I'm encountering what appears to be a regression of this issue on a file with a lot of small folds.

The file that's triggering it is a ledger3 ledger.  It contains about 1290 transactions.  Each is its own top-level fold, with a median fold length of 3 lines.

I briefly thought about porting FastFold to lua, but it doesn't seem to be slow itself.  Whatever's slow isn't where the profiler can find it.

For me, the steps to reproduce this are:

    :profile start profile.log
    :profile func *
    :profile file *
    e home.ledger
    :profile pause
    :noautocmd qall!

Functions sorted on total time:

    count  total (s)   self (s)  function
       11  10.264574   0.000600  <SNR>52_UpdateWin()
       22  10.263974  10.262231  <SNR>52_WinDo()
       10   0.101446   0.087435  <SNR>13_LoadFTPlugin()
       25   0.097044   0.089698  LedgerFoldText()
       10   0.014447   0.008185  <SNR>4_SynSet()
        2   0.006196   0.000206  <SNR>25_record()
        2   0.005990   0.001014  <SNR>25_addtomrufs()
       10   0.005406   0.004450  <SNR>14_LoadIndent()
       50   0.004372             <SNR>73_get_columns()
       75   0.002974             <SNR>73_multibyte_strlen()
        1   0.002684   0.000037  <SNR>25_savetofile()
        1   0.002647   0.002610  ctrlp#utils#writecache()
        1   0.002292   0.000977  <SNR>25_mergelists()
       11   0.001076   0.000457  <SNR>52_EnterWin()
        1   0.000994   0.000269  ctrlp#mrufiles#cachefile()
       11   0.000667             <SNR>52_LeaveWin()
       10   0.000619   0.000325  <SNR>52_Skip()
        2   0.000418             <SNR>63_Highlight_Matching_Pair()
        1   0.000299             ctrlp#utils#readfile()
        1   0.000266   0.000165  ctrlp#utils#opts()

And the top two targets of blame:

    FUNCTION  <SNR>52_UpdateWin()
    Called 11 times
    Total time:  10.264574
     Self time:   0.000600

    count  total (s)   self (s)
                                  " skip if another session still loading
       11              0.000110   if a:check && exists('g:SessionLoad') | return | endif

       11              0.000053   let s:curwin = winnr()
       11  10.261160   0.000189   call s:WinDo('if winnr() is s:curwin | call s:LeaveWin() | endif')
       11   0.003186   0.000183   call s:WinDo('if winnr() is s:curwin | call s:EnterWin() | endif')

    FUNCTION  <SNR>52_WinDo()
    Called 22 times
    Total time:  10.263974
     Self time:  10.262231

    count  total (s)   self (s)
                                  " avoid errors in CmdWin
       22              0.000248   if exists('*getcmdwintype') && !empty(getcmdwintype())
                                    return
                                  endif
                                  " Work around Vim bug.
                                  " See https://groups.google.com/forum/#!topic/vim_dev/LLTw8JV6wKg
       22              0.000177   let curaltwin = winnr('#') ? winnr('#') : 1
       22              0.000088   let currwin=winnr()
       22              0.000378   if &scrollopt =~# '\<jump\>'
       22              0.000168     set scrollopt-=jump
       22              0.000091     let l:restore = 'set scrollopt+=jump'
       22              0.000026   endif
       22  10.261173  10.259430   silent! execute 'keepjumps noautocmd windo ' . a:command
       22              0.000558   silent! execute 'noautocmd ' . curaltwin . 'wincmd w'
       22              0.000322   silent! execute 'noautocmd ' . currwin . 'wincmd w'
       22              0.000162   if exists('l:restore')
       22              0.000270     exe l:restore
       22              0.000033   endif

    FUNCTION  <SNR>52_LeaveWin()
    Called 11 times
    Total time:   0.000667
     Self time:   0.000667

    count  total (s)   self (s)
       11              0.000075   if exists('w:predifffdm')
                                    if empty(&l:foldmethod) || &l:foldmethod is# 'manual'
                                      let &l:foldmethod = w:predifffdm
                                      unlet w:predifffdm
                                      return
                                    elseif &l:foldmethod isnot# 'diff'
                                      unlet w:predifffdm
                                    endif
                                  endif

       11              0.000079   if exists('w:lastfdm') && &l:foldmethod is# 'diff'
                                    let w:predifffdm = w:lastfdm
                                  endif

       11              0.000070   if exists('w:lastfdm') && &l:foldmethod is# 'manual'
        1              0.000007     if !exists('b:last_changedtick') || b:changedtick > b:last_changedtick
                                      let &l:foldmethod = w:lastfdm
                                      let b:last_changedtick = b:changedtick
                                    else
        1              0.000003       let w:unchanged = 1
        1              0.000001     endif
        1              0.000001   endif
