### ISSUE TITLE
calling vim-go plugin :GoFmt causes all folds to close in current buffer

### ISSUE THREAD

**Issue by oryband** [Konfekt/FastFold#31]
When using [vim-go](https://github.com/fatih/vim-go) along with FastFold, and calling `:GoFmt`, all folds are closed in the curretn buffer. This happens either when setting `let g:go_fmt_autosave = 0` or to `= 1` (and saving the buffer, which triggers `:GoFmt`).

This really hurts the workflow, since it causes the user to lose its cursor on every buffer save. Only solution I have for now is to turn off calling `:GoFmt` on save.

Any idea why this happens and how to solve this?

**Comment by oryband** [comment]
update: I noticed this also happens when calling the variable refactor function `:GoRename`

**Comment by Konfekt** [comment]
Ahhhh, there has Allready been a Thread in go-lang Discussing this and a Patch for it, probably not in Master Yet.

**Comment by Konfekt** [comment]
Herne we go: https://github.com/fatih/vim-go/issues/502#issuecomment-182636048

**Comment by oryband** [comment]
@Konfekt thanks! awesome maintainer you are

**Comment by oryband** [comment]
for docs sake, the pr is at fatih/vim-go#691
