### ISSUE TITLE
Slow/nvim

### ISSUE THREAD

**Issue by carlitux** [Konfekt/FastFold#34]
It is too slow with neovim with python file and it is folding all file on load.

**Comment by Konfekt** [comment]
What is your fold method? FastFold doesn't fold indent folds. Please provide a mininmal vimrc and an example python file. If it's too slow, indent folding is quite fast itself, so no need to use FastFold?

**Comment by carlitux** [comment]
Looks like was related about other plugin... now it is working well. Closing it.
