### ISSUE TITLE
restore foldmethod after :diffsplit and :diffoff

### ISSUE THREAD

**Issue by Konfekt** [Konfekt/FastFold#36]
After :diffsplit and :diffoff, the `w:lastfdm` foldmethod is undefined, and `&l:foldmethod` is `manual`. Instead, `w:lastfdm` should equal the value of `w:lastfdm` before `:diffsplit`.

**Comment by lervag** [comment]
I'm curious, do you know any workaround here? I'd strongly appreciate a solution to this issue. I quite often end up with out of sync foldmethods. :\

**Comment by Konfekt** [comment]
It's been a while. The whole autocmd timing is convoluted enough that I almost expect it to fail sometimes after diffs. Still, I cannot reproduce it (on Vim 8.0.1568):

If the number of lines of the buffer is `< g:fastfold_minlines`, then there is no `w:lastfdm`. Otherwise it seems to work as well (using `expr` folds of [vimtex](https://github.com/lervag/vimtex/): 

1. Open a file by `vim 1.tex`
1. Hitting `zuz` shows `expr` folds to be updated
1. Call `:diffsplit 2.tex`
1. Hitting `zuz` shows `diff` folds to be updated
1. Call `:diffoff`
1. Hitting `zuz` shows `expr` folds to be updated

Note that `:diffoff` only applies to the current window; `:diffoff!` to all windows in the current tab page. Then `zuz` shows `expr` folds to be updated in all windows of the tab page.

**Comment by lervag** [comment]
I can relate to the importance of reproducability. I'll keep this in mind, and if I encounter the problem I'll try and figure out how to reproduce it. Could we keep the issue open for some more time? If you don't hear from me within a couple of weeks, then of course, feel free to close the issue.

**Comment by Konfekt** [comment]
Of course! I rather expect it to persist but hard to pinpoint.

**Comment by lervag** [comment]
Ok, I haven't been able to reproduce. Let's just close the issue.

**Comment by Konfekt** [comment]
Somewhat glad to hear as the whole autocmd logic slowly grew above my head.
