### ISSUE TITLE
Possible conflict with easymotion in off my one error

### ISSUE THREAD

**Issue by thalesmello** [Konfekt/FastFold#38]
I think I've located some kind of weird bug when using FastFold and easymotion.

The first time I've encountered this weird bug, I though it was related to only easymotion, so I have created an [issue report](https://github.com/easymotion/vim-easymotion/issues/292).

In the past couple of weeks, I've removed FastFold from my list of plugins. Strangely, the bug stopped happening. Yesterday, I decided to install FastFold again. To my surprise, the bug came back.

Could you help me identify what's happening?

Steps to reproduce the bug (taken from the easymotion issue I've created):

Have easymotion and FastFold. A minimal vimrc using vimplug would be as follows:

```
call plug#begin()
Plug 'easymotion/vim-easymotion'
Plug 'Konfekt/FastFold'
call plug#end()
```

In an empty buffer, type in:

	print('hello world')

Then, with the cursor in the in the first position, type `c<leader><leader>f'a`. As expected, the output is:

	hello world')

Now, press `u` to undo and create a split with an empty buffer using `:vnew`.
Apply the same `c<leader><leader>f'a` at the beginning of the first buffer text. The resulting output is:

	'hello world')

Which I believe is a bug. I've noticed it only acts when live editing the code. If you `u` undo the operation and `.` repeat it with `vim.repeat`, it applies the correct behavior. And, if you close the newly spawned buffer with `:q`, the correct operation starts to work again.

**Comment by Konfekt** [comment]
Hello, thanks for reporting this tricky bug.  Perhaps it is even a Vim bug. Regarding FastFold, the crucial line is
```vim
    if exists('##OptionSet')
      autocmd OptionSet foldmethod call s:UpdateBuf(0)
    endif
```
Can you confirm that commenting it out resolves the bug? I do not see how this check results in a one-character offset though. 

It is only there for convenience. If the user changes the current fold method manually, then FastFold stays active. Otherwise, only after a hook or `zuz` is hit.

**Comment by thalesmello** [comment]
Yes. I can confirm it. By just commenting out those lines, it gets removed.

So, what would be the appropriate thing to so here?

Create an option variable to make to avoid this autocmd being created?

**Comment by Konfekt** [comment]
I think best would be if easymotion not unnecessarily sets this variable. Otherwise I'd disable it by default.

**Comment by Konfekt** [comment]
By default, master now disables this autocmd and documents it as an option.

**Comment by thalesmello** [comment]
@Konfekt Thanks for the help. Should we close this issue, then?

**Comment by Konfekt** [comment]
Yeah, wondering how common this issue is and if disabling it by default is overcautious, but fine for now.
