### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by wikimatze** [Konfekt/FastFold#39]
Hi, deine bitbucket URL ist nicht aufrufbar. Kannst du mir bitte nochmal deine vimtex config zukommen lassen?

Thx!

**Comment by Konfekt** [comment]
Klar, aber sollte doch klappen. Ist public. Selber Name wie hier. Checke später mal ob es von woanders Probleme beim Clonen gibt.

**Comment by Konfekt** [comment]
Du musst zum Schluss zur https Adresse  .git hinzufügen.

**Comment by wikimatze** [comment]
Okay, habs gefunden. Das ist ja echt ne Wunderkiste, was da alles so drinsteckt!

**Comment by wikimatze** [comment]
Wie genau hast du die spezielle Shell im awesome window manager aufgerufen? Welche Datei ist das bei dir?

**Comment by Konfekt** [comment]
Jo, das ist die `zshrun.sh`. Die .zshrc checkt ob die variable `zshrun` definiert ist, und ruft dann die `zshrun` auf.

**Comment by wikimatze** [comment]
Wird gleich ausprobiert, sobald ich mit deinen vimtex-settings durch bin.

**Comment by Konfekt** [comment]
Der Aufruf vom zshrun ist in der rc.lua. Ist aber alles copyright https://github.com/majutsushi/etc
