### ISSUE TITLE
.go files doesn't auto-fold on open

### ISSUE THREAD

**Issue by oryband** [Konfekt/FastFold#4]
When opening `.go` files, no folding is initially applied until I manually `zuz`. Note I'm using [vim-go][vim-go] plugin.

[vim-go]: https://github.com/fatih/vim-go

**Comment by oryband** [comment]
Just updated, after a very long pause on this issue - and the problem still persists. Any progress?

**Comment by Konfekt** [comment]
Add `set foldlevel = 0` and `set foldlevelstart = 0` to .vimrc and tell me if everything is still unfolded. Do you use plugins that restore buffer settings like `restore_view`?

**Comment by oryband** [comment]
@Konfekt tried adding `set foldlevelstart = 0` and results are same.
Tried `grep`ping for `restore_view`, and [this is the only function](https://github.com/terryma/vim-multiple-cursors/blob/master/autoload/multiple_cursors.vim#L349) from the only plugin other than yours that has this string. I barely use this plugin and I think it activates itself only by a certain keypress - thus it shouldn't interfere with your plugin.

**Comment by oryband** [comment]
@Konfekt [here are my relevant folding](https://github.com/oryband/dotvim/blob/master/.vimrc#L191) settings in my `.vimrc`.

**Comment by Konfekt** [comment]
Hmm... can you also grep for `fold` or `fd`, especially `fdm` ? Does it subsist if you disable all plugins other than go-vim or FastFold? Can you paste the output of `autocmd FileType go`?

**Comment by Konfekt** [comment]
I noticed that when a ftplugin sets  `foldlevel` explicitly then a buffer of the corresponding filetype always starts with that foldlevel. But greping at github in your dotfiles and that of vim-go for `fold` or `fd` did not yield any results. Perhaps github is missing something, and you could grep for `fold` and `fd` in your `~/.vim`? 

This disappears without the `vim-go` plugin?

**Comment by Konfekt** [comment]
How about another swirl ?

**Comment by oryband** [comment]
hey @Konfekt will do next week! :)

**Comment by Konfekt** [comment]
Please reopen if the issue persists.

**Comment by oryband** [comment]
ok, sorry for the delays.

**Comment by oryband** [comment]
just wanted to updated that this issue has been resolved for me, don't know how, why, or when.

**Comment by Konfekt** [comment]
:+1:
