### ISSUE TITLE
How would I map a key to the movement command?

### ISSUE THREAD

**Issue by Alok** [Konfekt/FastFold#42]
I want to map `f` to FastFold's `za`'s current functionality. How would I do that?

**Comment by Konfekt** [comment]
If `za` can stay as is, then add `nmap f za` to the `.vimrc`.

If you want to leave `za` untouched, then add to the `.vimrc`:
```
let g:fastfold_fold_command_suffixes = ['x','X','A','o','O','c','C']
nnoremap f :<c-u>FastFoldUpdate<CR>za
```
