### ISSUE TITLE
FastFold error when opening split (only on first open split)

### ISSUE THREAD

**Issue by kthibodeaux** [Konfekt/FastFold#44]
After latest update when opening a split this error appears.  Once I mash enter until the error goes away it does not happen anymore for that neovim instance.
![2017-01-14-151104_703x181_scrot](https://cloud.githubusercontent.com/assets/1099465/21957740/da209172-da6b-11e6-9cac-98c1eec30d8e.png)

**Comment by Konfekt** [comment]
Please check again with the latest commit.

**Comment by kthibodeaux** [comment]
I no longer get the error.  Thank you!
