### ISSUE TITLE
error message when switching buffers

### ISSUE THREAD

**Issue by y** [Konfekt/FastFold#45]
After updating to b2734410c474373d9be02c2a6d6bb068a9bfd948 I get the following error message when switching buffers the first time:

    Error detected while processing function <SNR>45_LeaveWin:
    line   16:
    E121: Undefined variable: b:last_changedtick
    E15: Invalid expression: b:changedtick > b:last_changedtick

**Comment by Konfekt** [comment]
Please check again with the latest commit.

**Comment by mhartington** [comment]
I'm seeing this as well, even with  this commit https://github.com/Konfekt/FastFold/commit/fa4d9b8a8f3621a06596ee04bdccc78ab8a80e44

I'm only seeing it in neovim, when cycling though deoplete completions with `<c-n>`/`<c-p>`
After getting the warning once, it cannot be replicated unless you quit nvim and open it again.

**Comment by Alok** [comment]
I'm getting this too.

**Comment by Konfekt** [comment]
Please try the latest commit again, perhaps the variables weren't initialized on Vim startup.

**Comment by y** [comment]
tried the latest commit and error message no longer appears, but a worse problem now happens. if i open multiple files from the commandline (e.g. `vim a.py b.py c.py`), the focus is put on the last file and it's syntax is reset to nothing (ft='').

**Comment by Konfekt** [comment]
Noe better?

**Comment by mhartington** [comment]
So far it's been good for me. I'll report if I see it again though

**Comment by y** [comment]
> Noe better?

yes, both issues are resolved now
