### ISSUE TITLE
Error due to undefined b:last_changedtick

### ISSUE THREAD

**Issue by lervag** [Konfekt/FastFold#46]
Hi. For some reason, I am experiencing the following error after I change buffer the first time in a Vim session:

```
Error detected while processing function <SNR>96_LeaveWin:
line   16:
E121: Undefined variable: b:last_changedtick
E15: Invalid expression: b:changedtick > b:last_changedtick
```

This occurs in `plugin/fastfold.vim`, here:

```vim
function! s:LeaveWin()
  ...
  if exists('w:lastfdm') && &l:foldmethod is# 'manual' 
    if b:changedtick > b:last_changedtick
      let &l:foldmethod = w:lastfdm
      let b:last_changedtick = b:changedtick
    else
      let w:unchanged = 1
    endif
  endif
endfunction
```

I am trying to find a reproducible example, but it is not that easy. The problem occurs when changing journal date through my vimwiki clone, and it happened in another case earlier. I'll update when I find an example that is reproducible.

**Comment by lervag** [comment]
The problem seems to be that the autocommand

```vim
    autocmd BufEnter,WinEnter * 
          \ if !exists('b:last_changedtick') | let b:last_changedtick = b:changedtick | endif
```

is not fired. This is quite interesting, because one should think that one of these would be run on startup when loading the first buffer..?

However, it would be quite easy to solve this by using `get()` in the conditional in `s:LeaveWin`.

**Comment by Konfekt** [comment]
Oh... is it latest master? The version a few commits ago had the autocmd set up after VimEnter, too late. Yours must be that faulty one. Because s:LeaveWin is now only called by autocmds set up after that cited by you above.

**Comment by lervag** [comment]
Sorry, silly me forgot to `git pull` before submitting the issue. :)
