### ISSUE TITLE
"E121: Undefined variable: b:last_changedtick" on opening quickfix window

### ISSUE THREAD

**Issue by wilywampa** [Konfekt/FastFold#47]
This bug occurs if the quickfix window is opened automatically after `QuickFixCmdPost` and folding in the quickfix window is enabled as described here: http://vim.wikia.com/wiki/Fold_quickfix_list_on_directory_or_file_names#Folding_output_from_vimgrep

Apparently that causes the `BufLeave` or `WinLeave` autocommand to trigger without the `BufEnter` autocommand being triggered. To reproduce, create the `qf_fold.vim` file in your ftplugin directory as described in the link above, add a `QuickFixCmdPost` autocommand to call `:cwindow`, then do anything that uses the quickfix window.

**Comment by Konfekt** [comment]
How about adding a WinEnter event? Let's give it a try.

**Comment by wilywampa** [comment]
Thanks for the quick response but unfortunately that did not fix it. Why not change

```vim
if b:changedtick > b:last_changedtick
```
to
```vim
if b:changedtick > get(b:, 'last_changedtick', b:changedtick)
```

**Comment by Konfekt** [comment]
That `b:last_changedtick` does not exist does not imply that the buffer did not change. The `b:last_changedtick` is supposed to track these changes, by initializing the variable when entering the buffer. (It is meant as a speed-up: If neither content nor fold method  changed, then don't recompute.)

**Comment by Konfekt** [comment]
Well, I went for both.

**Comment by wilywampa** [comment]
Thanks!
