### ISSUE TITLE
Slowness in WinDo again

### ISSUE THREAD

**Issue by rcaputo** [Konfekt/FastFold#48]
I'm encountering what appears to be a regression of issue #28 in a file with a lot of small folds.

The file that's triggering it is a ledger3 ledger.  It contains about 1290 transactions, each of which is its own top-level fold.  Median fold length is 3 lines.

I briefly thought about porting FastFold to lua, but it doesn't seem to be slow itself.  Whatever's slow isn't where the profiler can find it.

For me, the steps to reproduce this are:

    :profile start profile.log
    :profile func *
    :profile file *
    e home.ledger
    :profile pause
    :noautocmd qall!

Functions sorted on total time:

    count  total (s)   self (s)  function
       11  10.264574   0.000600  <SNR>52_UpdateWin()
       22  10.263974  10.262231  <SNR>52_WinDo()
       10   0.101446   0.087435  <SNR>13_LoadFTPlugin()
       25   0.097044   0.089698  LedgerFoldText()
       10   0.014447   0.008185  <SNR>4_SynSet()
        2   0.006196   0.000206  <SNR>25_record()
        2   0.005990   0.001014  <SNR>25_addtomrufs()
       10   0.005406   0.004450  <SNR>14_LoadIndent()
       50   0.004372             <SNR>73_get_columns()
       75   0.002974             <SNR>73_multibyte_strlen()
        1   0.002684   0.000037  <SNR>25_savetofile()
        1   0.002647   0.002610  ctrlp#utils#writecache()
        1   0.002292   0.000977  <SNR>25_mergelists()
       11   0.001076   0.000457  <SNR>52_EnterWin()
        1   0.000994   0.000269  ctrlp#mrufiles#cachefile()
       11   0.000667             <SNR>52_LeaveWin()
       10   0.000619   0.000325  <SNR>52_Skip()
        2   0.000418             <SNR>63_Highlight_Matching_Pair()
        1   0.000299             ctrlp#utils#readfile()
        1   0.000266   0.000165  ctrlp#utils#opts()

And the top two targets of blame:

    FUNCTION  <SNR>52_UpdateWin()
    Called 11 times
    Total time:  10.264574
     Self time:   0.000600

    count  total (s)   self (s)
                                  " skip if another session still loading
       11              0.000110   if a:check && exists('g:SessionLoad') | return | endif

       11              0.000053   let s:curwin = winnr()
       11  10.261160   0.000189   call s:WinDo('if winnr() is s:curwin | call s:LeaveWin() | endif')
       11   0.003186   0.000183   call s:WinDo('if winnr() is s:curwin | call s:EnterWin() | endif')

    FUNCTION  <SNR>52_WinDo()
    Called 22 times
    Total time:  10.263974
     Self time:  10.262231

    count  total (s)   self (s)
                                  " avoid errors in CmdWin
       22              0.000248   if exists('*getcmdwintype') && !empty(getcmdwintype())
                                    return
                                  endif
                                  " Work around Vim bug.
                                  " See https://groups.google.com/forum/#!topic/vim_dev/LLTw8JV6wKg
       22              0.000177   let curaltwin = winnr('#') ? winnr('#') : 1
       22              0.000088   let currwin=winnr()
       22              0.000378   if &scrollopt =~# '\<jump\>'
       22              0.000168     set scrollopt-=jump
       22              0.000091     let l:restore = 'set scrollopt+=jump'
       22              0.000026   endif
       22  10.261173  10.259430   silent! execute 'keepjumps noautocmd windo ' . a:command
       22              0.000558   silent! execute 'noautocmd ' . curaltwin . 'wincmd w'
       22              0.000322   silent! execute 'noautocmd ' . currwin . 'wincmd w'
       22              0.000162   if exists('l:restore')
       22              0.000270     exe l:restore
       22              0.000033   endif

Mysteriously, `LeaveWin()` isn't slow at all:

    FUNCTION  <SNR>52_LeaveWin()
    Called 11 times
    Total time:   0.000667
     Self time:   0.000667

    count  total (s)   self (s)
       11              0.000075   if exists('w:predifffdm')
                                    if empty(&l:foldmethod) || &l:foldmethod is# 'manual'
                                      let &l:foldmethod = w:predifffdm
                                      unlet w:predifffdm
                                      return
                                    elseif &l:foldmethod isnot# 'diff'
                                      unlet w:predifffdm
                                    endif
                                  endif

       11              0.000079   if exists('w:lastfdm') && &l:foldmethod is# 'diff'
                                    let w:predifffdm = w:lastfdm
                                  endif

       11              0.000070   if exists('w:lastfdm') && &l:foldmethod is# 'manual'
        1              0.000007     if !exists('b:last_changedtick') || b:changedtick > b:last_changedtick
                                      let &l:foldmethod = w:lastfdm
                                      let b:last_changedtick = b:changedtick
                                    else
        1              0.000003       let w:unchanged = 1
        1              0.000001     endif
        1              0.000001   endif

**Comment by Konfekt** [comment]
Thank you for the profiling! There are autocmd's being triggered when entering and leaving buffers. For example
```vim
    autocmd BufEnter,WinEnter *
          \ if &l:foldmethod isnot# 'diff' && exists('b:predifffdm') | call s:UpdateBuf(0) | endif
```
and
```vim
function! s:UpdateBuf(feedback)
  let s:curbuf = bufnr('%')
  call s:WinDo("if bufnr('%') is s:curbuf | call s:LeaveWin() | endif")
  call s:WinDo("if bufnr('%') is s:curbuf | call s:EnterWin() | endif")

  if !a:feedback | return | endif

  if !exists('w:lastfdm')
    echomsg "'" . &l:foldmethod . "' folds already continuously updated"
  else
    echomsg "updated '" . w:lastfdm . "' folds"
  endif
endfunction
```
That `LeaveWin()` is not slow, does imply that `EnterWin()` is slow?
```vim
function! s:EnterWin()
  if exists('w:unchanged')
    unlet w:unchanged
  elseif s:Skip()
    if exists('w:lastfdm')
      unlet w:lastfdm
    endif
  else
    let w:lastfdm = &l:foldmethod
    setlocal foldmethod=manual
  endif
endfunction
```
One would guess that `LeaveWin()` is slow though, because it sets the foldmanual to something non-manual.

There are a lot of intertwined autocmd's, that is probably why it is hard to pinpoint where the actual work is happening.

To be honest: I never understood why the `windo ...` command would trigger the update of all folds, it just does and FastFold makes good use of it.

If there are a 1000 folds, folding is probably very slow without fastfold in any case.
This is just the time it takes to update them?
What time does `:FastFoldUpdate<cr>` give?

**Comment by Konfekt** [comment]
By your log,
```vim
  autocmd BufWinEnter,FileType          * call s:UpdateWin(1)
```
is triggered.
It is probably due to the `BufWinEnter` event.
This is, you are entering the buffer, for example, after switching tabs?

**Comment by Konfekt** [comment]
Ok, I think your profile says that it happens on opening the file. So all kinds of autocmd's are triggered. Isn't this simply due to the huge amount of folds being computed? What happens without FastFold?

**Comment by rcaputo** [comment]
Thanks for looking into this and prompting me to try without FastFold. It looks like your script is taking the blame for something else.  I'm going to close this issue and start removing things to narrow it down.

    % time vim -c ':q' home.ledger
    vim -c ':q' home.ledger  0.84s user 0.47s system 90% cpu 1.445 total

    % mv ~/.vim/bundle/vim-fastfold ~/.vim/

    % time vim -c ':q' home.ledger
    vim -c ':q' home.ledger  0.84s user 0.48s system 89% cpu 1.476 total

**Comment by Konfekt** [comment]
Ok. After all, it would be interesting to know how much time the computation of the folds takes. Maybe it simply takes 10 seconds. In this case, perhaps
```vim
	syn sync maxlines=80
	syn sync minlines=20
```
speeds things up a bit.

**Comment by rcaputo** [comment]
You say `windo` recalculates all folds?  Would it being called 11 times mean that all folds are recalculated 11 times?

It's definitely slower to switch into the buffer from another, or to edit the file with `:e` inside vim, than it is to open the file from the shell. For example, this and all the ones like it, finish well under 10sec:

    % time vim -c ':redraw' -c ':q' home.ledger
    vim -c ':redraw' -c ':q' home.ledger  1.49s user 0.84s system 89% cpu 2.597 total

Simulating something that's slow in-editor also finishes relatively fast:

    % time vim -c ':e home.ledger' -c ':wincmd v' -c ':redraw' -c ':e deleteme.now' -c ':redraw' -c ':wincmd l' -c ':redraw' -c ':qall'
    vim -c ':e home.ledger' -c ':wincmd v' -c ':redraw' -c ':e deleteme.now' -c    1.60s user 0.91s system 94% cpu 2.653 total

Narrowing the `syn sync` window doesn't seem to matter:

    % time vim --cmd 'syn sync maxlines=80' --cmd 'syn sync minlines=20' -c ':redraw' -c ':q' home.ledger
    vim --cmd 'syn sync maxlines=80' --cmd 'syn sync minlines=20' -c ':redraw' -c  1.49s user 0.84s system 90% cpu 2.568 total

Adding a `:FastFoldUpdate` nudges the wall time up by almost half a second. It returns without perceptible lag when I execute it manually.

    % time vim --cmd 'syn sync maxlines=80' --cmd 'syn sync minlines=20' -c ':FastFoldUpdate' -c ':redraw' -c ':q' home.ledger
    vim --cmd 'syn sync maxlines=80' --cmd 'syn sync minlines=20' -c  -c ':redraw  1.49s user 0.85s system 80% cpu 2.912 total

**Comment by rcaputo** [comment]
I have to contradict myself. Removing FastFold makes `:e` in the editor and entering the ledger buffer, about 5x faster.

It seems that `vim -c ':q' home.ledger` is bypassing FastFold, or something that FastFold is triggering.

**Comment by Konfekt** [comment]
Yes, `windo` updates the folds. If it is called 22 times, and Vim is not smart about it, this I don't know, then folds are update 22 times. Somehow `windo` triggers the update of folds. (The idea is also that even though a tab might show a single buffer, the folds are per window, so a windo is needed.) 

You  say that a `FastFoldUpdate` takes half a second by profiling. Is this also what you perceive after making a change and running it manually?

**Comment by rcaputo** [comment]
I don't notice a delay when I run `:FastFoldUpdate` by hand.

**Comment by rcaputo** [comment]
My `vim -c` benchmarks may be running significantly faster because they're only triggering `WinDo()` once.

I was able to turn on profiling before loading my .vimrc.

    % vim --cmd ':profile start profile.log' --cmd ':profile func *' --cmd ':profile file *'  home.ledger

And `WinDo()` only executed once:
 
    FUNCTIONS SORTED ON TOTAL TIME
    count  total (s)   self (s)  function
        1   0.931209   0.000428  <SNR>31_init()
        1   0.930781   0.000159  <SNR>31_UpdateTab()
        2   0.930622   0.930403  <SNR>31_WinDo()
       31   0.086378   0.078897  LedgerFoldText()
        1   0.040603   0.000226  pathogen#infect()
        1   0.035647   0.000671  pathogen#cycle_filetype()
       10   0.033745   0.020146  <SNR>13_LoadFTPlugin()
        1   0.028936   0.028120  pathogen#helptags()
       10   0.013698   0.007801  <SNR>4_SynSet()
        1   0.004643   0.000505  pathogen#interpose()
       10   0.004409   0.003733  <SNR>14_LoadIndent()
       62   0.004051             <SNR>51_get_columns()
        1   0.003814   0.000072  <SNR>24_record()
        1   0.003742   0.000377  <SNR>24_addtomrufs()
       53   0.003474             AlignMaps#MakeMap()
       93   0.003430             <SNR>51_multibyte_strlen()
        1   0.001809   0.000842  <SNR>24_mergelists()
        1   0.001556   0.000028  <SNR>24_savetofile()
        1   0.001528   0.001502  ctrlp#utils#writecache()
       16   0.001240   0.000809  pathogen#is_disabled()

**Comment by Konfekt** [comment]
You have to make changes, to increase `b:change_tick` before running `:FastFoldUpdate<cr>` for `s:windo()` to have any effect. Did you do so? Otherwise I am at loss why it takes 20 seconds on entering the buffer, but felt 0 on updating manually.

**Comment by rcaputo** [comment]
`b:changedtick` is 2 after I `:e home.ledger`.  It'd have to be a lot more than that.

If I understand the code, it looks like vim's `windo` is invoked regardless of `b:changedtick`.  I did this to check whether it triggers the slowdown:

    :let t = reltime() | :windo echo expand("%") . ' = ' . reltimestr(reltime(t))

And I ran it in vim with two files open: an empty text file named "foo" and "home.ledger".  The results seem to confirm it:

    foo =   0.000084
    home.ledger =   5.226913

Possibly significant: It runs fast when home.ledger is the only file open:

    home.ledger =   0.000044

**Comment by rcaputo** [comment]
I re-ran my little `reltime()` test with profiling enabled. I don't know what it means yet that `windo` was called several times while I was doing `windo`, but at least it doesn't seem to have gone into an infinite loop or recursion.

    FUNCTIONS SORTED ON TOTAL TIME
    count  total (s)   self (s)  function
        5   5.965839   0.000233  <SNR>31_UpdateWin()
       10   5.965606   5.964751  <SNR>31_WinDo()
        5   0.136855   0.129422  <SNR>13_LoadFTPlugin()
        4   0.038217   0.000251  <SNR>24_record()
        4   0.037966             <SNR>24_addtomrufs()
        5   0.037437   0.032649  <SNR>4_SynSet()
        5   0.028223   0.027700  <SNR>14_LoadIndent()
       13   0.001446             <SNR>31_LeaveWin()
       13   0.000786   0.000485  <SNR>31_EnterWin()
        2   0.000371             <SNR>42_Highlight_Matching_Pair()
        5   0.000301   0.000168  <SNR>31_Skip()
        2   0.000181             <SNR>43_LocalBrowse()
        5   0.000093             <SNR>31_inSkipList()
        5   0.000040             <SNR>31_isReasonable()

    FUNCTIONS SORTED ON SELF TIME
    count  total (s)   self (s)  function
       10   5.965606   5.964751  <SNR>31_WinDo()
        5   0.136855   0.129422  <SNR>13_LoadFTPlugin()
        4              0.037966  <SNR>24_addtomrufs()
        5   0.037437   0.032649  <SNR>4_SynSet()
        5   0.028223   0.027700  <SNR>14_LoadIndent()
       13              0.001446  <SNR>31_LeaveWin()
       13   0.000786   0.000485  <SNR>31_EnterWin()
        2              0.000371  <SNR>42_Highlight_Matching_Pair()
        4   0.038217   0.000251  <SNR>24_record()
        5   5.965839   0.000233  <SNR>31_UpdateWin()
        2              0.000181  <SNR>43_LocalBrowse()
        5   0.000301   0.000168  <SNR>31_Skip()
        5              0.000093  <SNR>31_inSkipList()
        5              0.000040  <SNR>31_isReasonable()

**Comment by rcaputo** [comment]
My previous test was in error. Using `:noautocmd windo` is a lot faster in the same environment. This makes less sense.

    :let t = reltime() | :noautocmd windo echo expand("%") . ' = ' . reltimestr(reltime(t))

Gives this:

    foo =   0.000057
    home.ledger =   0.000131

**Comment by rcaputo** [comment]
I've looked at this for a while today, and I've reached the point where it's becoming desirable to start giving up.  I've put this in my .vimrc:

    let g:fastfold_skip_filetypes = [ 'ledger' ]

But that doesn't seem to bypass the `windo` call.  Do `s:UpdateWin()`, `s:UpdateBuf()`, and `s:UpdateTab()` need to check `s:Skip()` before they call `s:WinDo()`?

**Comment by Konfekt** [comment]
True, it does not skip windo. It skips everything that is done inside `windo`. 

So `windo` takes 5 seconds because it triggers autocmd's, probably `WinEnter` and `WinLeave`. Could you disable either one of
```vim
    " Make &l:foldmethod local to Buffer and NOT Window.
    autocmd BufEnter,WinEnter *
          \ if exists('b:lastfdm') | let w:lastfdm = b:lastfdm | call s:LeaveWin() | call s:EnterWin() | endif
    autocmd BufLeave,WinLeave *
          \ call s:LeaveWin() | call s:EnterWin() |
          \ if exists('w:lastfdm')     | let b:lastfdm = w:lastfdm |
          \ elseif exists('b:lastfdm') | unlet b:lastfdm | endif
```
and see if this makes it faster?

**Comment by Konfekt** [comment]
What is curious though is that FastFold calls `windo` with `noautocmd`.

**Comment by rcaputo** [comment]
I agree it's curious that there's a slowdown in `noautocmd windo` in FastFold.  I can only reproduce a slowdown by omitting `noautocmd` in my own test.

Disabling the two autocmd statements you suggested didn't change anything, so I methodically went through `s:Init()`. Times are for this test:

    :let t = reltime() | :windo echo '    '  . expand("%") . ' = ' . reltimestr(reltime(t))

I commented out everyhing in `augroup FastFoldEnter` in `s:Init()` except the `autocmd!`:

    foo =   0.001605
    home.ledger =   0.031477

I then started retesting the time after enabling sections of `augroup FastfoldEnter` from the bottom up.

Enabling `Update folds on saving.` to the end:

    foo =   0.000089
    home.ledger =   0.030914

Enabling `Update folds on reload.` to the end:

    foo =   0.000095
    home.ledger =   0.030389

Enabling `So that FastFold functions correctly after :loadview.` to the end:

    fo =   0.000095
    home.ledger =   0.028913

Enabling `BufWinEnter = to change &l:foldmethod by modelines.` to the end slowed things down:

    foo =   0.000089
    home.ledger =   5.384902   **Time jump.**

So I disabled everything except `autocmd BufWinEnter,FileType * call s:UpdateWin(1)`:

    foo =   0.000094
    home.ledger =   5.086728  **Still high.**

Then I disabled everything but `autocmd TabEnter  * call s:UpdateTab()`:

    foo =   0.000044
    home.ledger =   0.030565  **Normal again.**

The time remained normal from then on.

Disabling everything but `autocmd BufLeave,WinLeave * if exists('w:predifffdm') ....`:

    foo =   0.000089
    home.ledger =   0.030612

Disabling everything but `autocmd BufEnter,WinEnter * if &l:foldmethod isnot# 'diff' ....`:

    foo =   0.000101
    home.ledger =   0.081302

Disabling everything but `autocmd BufLeave,WinLeave * call s:LeaveWin() | call s:EnterWin() ....`:

    foo =   0.000058
    home.ledger =   0.028820

Disabling everything but `autocmd BufEnter,WinEnter * if exists('b:lastfdm') ....`::

    foo =   0.000080
    home.ledger =   0.031909

**Comment by rcaputo** [comment]
I think I've verified that the `BufWinEnter,FileType` autocmd is involved somehow.

I added an `echo` to `s:Init()` like this:

    " BufWinEnter = to change &l:foldmethod by modelines.
    autocmd BufWinEnter,FileType          * call s:UpdateWin(1) | echo "autocmd"

I don't see that when I `vim home.ledger` from the shell.

Nor do I see it when I split the window with `C-ws`.

It makes its first appearance when I open a new file, as in `:e foo`:

    "foo" 0L, 0C
    autocmd
    Press ENTER or type command to continue

And it appears again when I switch from the "foo" window back to "home.ledger" with `C-wj`. Pardon my boring modeline.

    home.ledger                                                            1,1            Top
    autocmd

**Comment by rcaputo** [comment]
I've looked `noautocmd windo` a little more, and it still doesn't seem to make sense.  Maybe something else is happening, and it only looks like it's `windo`.

Documentation for `noautocmd` says it sets `eventignore=all` for one command.

Documentation for `eventignore` says it only works when the `+autocmd` feature is enabled.

My `:version` includes `+autocmd`.  I imagine I would have many more problems if it weren't enabled.

`:set ei` displays `eventignore=`.

`:noautocmd set ei` displays `eventignore=all`.

`:noautocmd echo &ei` displays `all`.

When I have two vim windows open, `:windo echo expand('%') | set ei` displays:

    foo
      eventignore=
    home.ledger
      eventignore=

`:noautocmd windo echo expand('%') | set ei` displays what we expect:

    foo
      eventignore=all
    home.ledger
      eventignore=all

**Comment by Konfekt** [comment]
Ok, so disabling 
```vim
autocmd TabEnter                      * call s:UpdateTab()
```
resolved the massive lag on entering?

Well, it is perhaps a redundant autocmd. There are so many events firing, on entering the window, buffer, Vim, I guess we could disable it and see what happens.

**Comment by rcaputo** [comment]
Sorry, I've edited my earlier comment to make it clearer.

What seems to solve it in my case is disabling `autocmd BufWinEnter,FileType * call s:UpdateWin(1)`.  To be sure, I did only this, and all window switching delay has gone away:

    diff --git a/plugin/fastfold.vim b/plugin/fastfold.vim
    index 19de8f8..b6fe589 100644
    --- a/plugin/fastfold.vim
    +++ b/plugin/fastfold.vim
    @@ -199,7 +199,7 @@ function! s:init()
         autocmd TabEnter                      * call s:UpdateTab()
    
         " BufWinEnter = to change &l:foldmethod by modelines.
    -    autocmd BufWinEnter,FileType          * call s:UpdateWin(1)
    +    "autocmd BufWinEnter,FileType          * call s:UpdateWin(1)
         " So that FastFold functions correctly after :loadview.
         autocmd SessionLoadPost               * call s:UpdateWin(0)

**Comment by Konfekt** [comment]
Ok, so is ist FileType or BufWinEnter? Could you remove each one of those and report on starting time and switching time, when using Vim.

**Comment by rcaputo** [comment]
Startup with just `FileType`:

    % time vim -c ':q' home.ledger
    vim -c ':q' home.ledger  0.81s user 0.46s system 91% cpu 1.378 total

Estimated switching time with just `FileType`:

    foo =   0.000096
    home.ledger =   4.853790

Startup with just `BufWinEnter`:

    % time vim -c ':q' home.ledger
    vim -c ':q' home.ledger  0.81s user 0.46s system 92% cpu 1.386 total

Estimated switching time with just `BufWinEnter`:

    foo =   0.000097
    home.ledger =   0.028776

**Comment by Konfekt** [comment]
Ok. That's curious. Does not make any sense to me. The FileType autocmd is there in case the foldmethod changes with the filetype. As the filetype is buffer-wise, not window-wise, though,  splitting up
```vim
autocmd BufWinEnter,FileType          * call s:UpdateWin(1)
```
into
```vim
autocmd BufWinEnter          * call s:UpdateWin(1)
autocmd FileType          * call s:UpdateBuf(0)
```
makes sense though. Does this improve anything?

**Comment by rcaputo** [comment]
Splitting the autocmd into two doesn't seem to make a difference.

Today I learned about `verbose`.  I directed verbose logging to a file and ran through my usual test scenario.  The output is attached.  Lines containing "!!!" are the output of `echo` commands I issued before performing each step.

    % grep '!!!' verbose.log
    !!! opening home.ledger
    !!! splitting window
    !!! opening foo
    !!! switching window from foo to home.ledger
    !!! done. quitting

[verbose.log](https://github.com/Konfekt/FastFold/files/1422636/verbose.log)

**Comment by rcaputo** [comment]
The verbose log is kind of nice.  I think I'm starting to see the problem:

    % egrep '!!!|filetype=ledger|Update' verbose.log | tail -14
    !!! switching window from foo to home.ledger
    autocommand if &l:foldmethod isnot# 'diff' && exists('b:predifffdm') | call s:UpdateBuf(0) | endif
    autocommand setlocal filetype=ledger | compiler ledger
    autocommand call s:UpdateBuf(0)
    autocommand setlocal filetype=ledger | compiler ledger
    autocommand call s:UpdateBuf(0)
    autocommand setlocal filetype=ledger | compiler ledger
    autocommand call s:UpdateBuf(0)
    autocommand setlocal filetype=ledger | compiler ledger
    autocommand call s:UpdateBuf(0)
    autocommand setlocal filetype=ledger | compiler ledger
    autocommand call s:UpdateBuf(0)
    autocommand if &l:foldmethod isnot# 'diff' && exists('b:predifffdm') | call s:UpdateBuf(0) | endif
    !!! done. quitting

**Comment by rcaputo** [comment]
It's probably a conflict with this file:

    % cat vim-ledger/ftdetect/ledger.vim
    autocmd BufEnter,BufRead *.ldg,*.ledger setlocal filetype=ledger | compiler ledger

When I enter a "ledger" buffer, the filetype is set to "ledger", which triggers `s:UpdateWin(0)`, which cycles the windows... and since `windo` seems to be triggering autocmds again, it re-enters the "ledger" window.

Changing it to this helps a lot.  I'll recommend this change to the other project.

    % cat vim-ledger/ftdetect/ledger.vim
    autocmd BufEnter,BufRead *.ldg,*.ledger if &l:filetype != 'ledger' | setlocal filetype=ledger | compiler ledger | endif

**Comment by Konfekt** [comment]
It is `BufEnter`. That should not be there. The filetype does NOT need to be set every time the buffer is entered, but only when it is read, created or the filename changed. Here's a sane example:
```vim
au BufRead,BufNewFile,BufFilePost *.{md,markdown,mdown,mkd,mkdn} set filetype=markdown
```
Perhaps @kljohann can improve on this in https://github.com/ledger/vim-ledger.

**Comment by Konfekt** [comment]
Apparently the filetype is only properly detected AFTER `BufEnter`. This is why
```vim
if &l:filetype != 'ledger' | setlocal filetype=ledger | compiler ledger | endif
```
does not work.

**Comment by rcaputo** [comment]
I've updated my ticket at vim-ledger to suggest removing `BufEnter` from their ftdetect.

**Comment by rcaputo** [comment]
Why `noautocmd windo` is triggering autocommands remains a mystery, but I don't feel a need to solve it here and now.

I consider this issue to be closed.  Thank you very much for your time and assistance.

**Comment by Konfekt** [comment]
Yeah, I am also relieved. Little makes sense when writing code for Vim. Holding everything together while understanding little makes you anxious. To some extent, why this plugin works is a mystery to me in view of the tangled net of autocmds.
