### ISSUE TITLE
manual folds not preserved when saving a perl file with perl_fold = 1

### ISSUE THREAD

**Issue by Jeansen** [Konfekt/FastFold#49]
I do not know, if I am missing something, but with  `foldmethod=manual` and `perl_fold = 1`,whenever I save my perl file, manual folds get deleted.

**Comment by Konfekt** [comment]
Yeah, that's true. It is impossible to preserve manual folds with FastFold, other than disabling it for that file type by
```vim
  let g:fastfold_skip_filetypes= [ 'perl' ]
```

**Comment by Jeansen** [comment]
@Konfekt Thanks for this super quick answer. Keep up the good work :smiley:
