### ISSUE TITLE
"no folds found" when using fastfold with vimwiki in markdown format

### ISSUE THREAD

**Issue by gauteh** [Konfekt/FastFold#51]
when I have fastfold enabled my vimwiki files (markdown) format do not get detected. I also have vim-stay, but only enabling vim-stay does not affect behavior. I have `let g:markdown_folding = 1` and `let g:vimwiki_folding = 'expr'`. I use vim-plug.

**Comment by gauteh** [comment]
Enno writes on August 29, 2018 22:21:
> Ah, I had the same problem I think, that is, vimwiki would not open wiki files as markdown, and had to switch to the wiki format. I have no idea how FastFold could interfere in the filetype setup, so I am surprised that FastFold is the cause.  

Yeah - tried pretty much any combination of config option that I thought 
could have any effect. Does it matter what I set `foldmethod` to for 
fastfold? 

Vimwiki has support for folding markdown (by which mechanism I am not 
sure), so I thought that FastFold would just pick that up? Even if 
ft=vimwiki?

> Can you produce it with a minimal setup? 

I'll give it a shot.

**Comment by Konfekt** [comment]
The followin `vimrc` return on `set fdm?`the foldmethod manual.

```vim
set nocompatible
language messages en_US  " To avoid scrambled non english letters.

" Load plugin
let &rtp = '~/.vim/plugged/vimiki,' . &rtp
let &rtp = '~/.vim/plugged/vimiki/after,' . &rtp

" call plug#begin('~/.vim/plugged')
"   Plug 'https://github.com/...'
" call plug#end()

filetype plugin indent on
syntax enable

" options go here

let g:vimwiki_ext2syntax = { '.wiki': 'markdown', }
let g:markdown_folding = 1
let g:vimwiki_folding = 'expr'

" ex:ft=vim 

```

**Comment by Konfekt** [comment]
Ok, but 
```
let g:markdown_folding = 1
```
is the foldmethod included by Vim. This means, as long as the filetype (check by `set filetype?`) remains wiki, it will not be used.

You should add into `~/.vim/ftplugin/wiki.vim` the lines
```
  setlocal foldexpr=MarkdownFold()
  setlocal foldmethod=expr
  let b:undo_ftplugin .= " foldexpr< foldmethod<"
```
from `/usr/share/vim/vim80/ftplugin/markdown.vim` to ensure markdown folding in wiki files.

**Comment by gauteh** [comment]
tor. 30. aug. 2018 kl. 13:15 skrev Enno <notifications@github.com>:

> Ok, but
>
> let g:markdown_folding = 1
>
> is the foldmethod included by Vim. This means, as long as the filetype
> (check by set filetype?) remains wiki, it will not be used.
>
> You should add into ~/.vim/ftplugin/wiki.vim the lines
>
>   setlocal foldexpr=MarkdownFold()
>   setlocal foldmethod=expr
>   let b:undo_ftplugin .= " foldexpr< foldmethod<"
>
> from /usr/share/vim/vim80/ftplugin/markdown.vim to ensure markdown
> folding in wiki files.
>

Yes, that was my understanding as well. But since it works without any of
that when using vimwiki (ft=vimwiki) I think that vimwiki handles markdown
folding already (unless having fastfold enabled).

**Comment by Konfekt** [comment]
Well, but then I cannot reproduce it by the minimal `vimrc`.

**Comment by gauteh** [comment]
Enno writes on August 30, 2018 16:47:
> Well, but then I cannot reproduce it by the minimal `vimrc`.

Yeah.. hm. Now I cannot reproduce it with the minimal vimrc, but still 
sometimes get it with my full vimrc.. don't know whats going on. Can 
probably close this.

**Comment by Konfekt** [comment]
And with the above workaround, it is fine?

**Comment by gauteh** [comment]
Seems like the whole issue disappeared -I’ll try if it pops up again

fre. 31. aug. 2018 kl. 20:14 skrev Enno <notifications@github.com>:
