### ISSUE TITLE
FastFold causes delays when switching Vimwiki windows

### ISSUE THREAD

**Issue by mMontu** [Konfekt/FastFold#54]
Continuing the discussion from https://github.com/vimwiki/vimwiki/commit/777569f95fba78408d2ee0cdddcd39e08b51d351#commitcomment-31868343

The latest commits reduced the delay indeed, but the issue still happens.
It can be reproduce with [this file](https://github.com/vimwiki/vimwiki/files/2590344/delay.zip) by running the following:

    $ gvim -u NONE -U NONE -N -i NONE
    <commands below can be copied to clipboard and run with `:@+`>
    set nocompatible
    filetype plugin on
    syntax on
    let g:vimwiki_camel_case = 0  " Don't make links from CamelCased words
    let g:vimwiki_table_auto_fmt = 0 " Turn off table auto-formatting
    let g:vimwiki_autowriteall = 0
    let g:vimwiki_folding = 'expr:quick'    " Enable folding.
    let &rtp.=',~/.vim/bundle/vimwiki'
    source ~/.vim/bundle/vimwiki/plugin/vimwiki.vim
    e ~/tmp/delay.wiki
    tabe
    let start = reltime() | tabprev | redraw | echom reltimestr(reltime(start))
    " echoes around 0.015s
    source ~/.vim/bundle/FastFold/plugin/fastfold.vim
    do VimEnter
    tabe
    let start = reltime() | tabprev | redraw | echom reltimestr(reltime(start))
    " echoes around 5.5s

**Comment by Konfekt** [comment]
Does this happen independently of `g:fastfold_fdmhook` ? I also removed the TabEnter autocmd, as it might be the culprit of a recomputation that takes such a toll and seems not stricly necessary.

**Comment by mMontu** [comment]
Without the TabEnter there is no delay, regardless of `g:fastfold_fdmhook` value.
Now it works like a charm!
Thanks!!
