### ISSUE TITLE
README documentation of g:fastfold_fold_command_suffixes = []

### ISSUE THREAD

**Issue by abarker** [Konfekt/FastFold#58]
In the README file it says: "If you prefer that folds are updated whenever you close or open folds by a standard keystroke such as zx,zo or zc, then add let g:fastfold_fold_command_suffixes = [] to your .vimrc."  Looking at the source, it seems that that should be "prefer that folds are not updated".

**Comment by Konfekt** [comment]
Indeed. Thank you!

**Comment by Konfekt** [comment]
Fixed by the latest commit.
