### ISSUE TITLE
explanation about different number meaning of setting

### ISSUE THREAD

**Issue by roachsinai** [Konfekt/FastFold#60]
```
let g:markdown_folding = 1
let g:tex_fold_enabled = 1
let g:vimsyn_folding = 'af'
let g:xml_syntax_folding = 1
let g:javaScript_fold = 1
let g:sh_fold_enabled= 7
let g:ruby_fold = 1
let g:perl_fold = 1
let g:perl_fold_blocks = 1
let g:r_syntax_folding = 1
let g:rust_fold = 1
let g:php_folding = 1
```

Readme and doc both has above content, but can't find the explanation of difference between `1`, `af` and `7`.

Could you please tell me the differences?

**Comment by Konfekt** [comment]
Gladly!

- The setting ` g:vimsyn_folding = 'af'` is documented in `:help ft-vim-syntax` in the paragraph `:help g:vimsyn_folding`. This setting enables folding in Vimscript buffers only for autocmd groups and functions.
- The number `7` is to be read by its binary expansion `111`as documented in `:help ft-sh-syntax`, meaning that folding is enabled for all the three options

    - functions,
    - heredoc (whatever that is), and
    - if conditionals and do/for loops

**Comment by roachsinai** [comment]
@Konfekt thank you so much!

**Comment by roachsinai** [comment]
Hi @Konfekt may I ask you where is the code let things like `let g:ruby_fold = 1` and `let g:perl_fold = 1` works?

As I found the doc of `ruby_fold` is provided by fastfold.vim, but I can't find i t in fastfold.vim.

![image](https://user-images.githubusercontent.com/9500049/103174974-7aac9f80-48a1-11eb-8fb0-b3bab386269d.png)

Thanks.

**Comment by Konfekt** [comment]
No problem, it is in `$VIMRUNTIME/syntax/ruby.vim`. For example,

```vim
" /usr/share/vim/vim80/syntax/ruby.vim (lines 22-24)
if has("folding") && exists("ruby_fold")
  setlocal foldmethod=syntax
endif
```

**Comment by roachsinai** [comment]
> No problem, it is in `$VIMRUNTIME/syntax/ruby.vim`. For example,
> 
> ```viml
> " /usr/share/vim/vim80/syntax/ruby.vim (lines 22-24)
> if has("folding") && exists("ruby_fold")
>   setlocal foldmethod=syntax
> endif
> ```

Thanks for quick reply! How about filetype like python? Is there any suggestion?

**Comment by Konfekt** [comment]
For Python `foldmethod=indent` is a simple popular choice, or try https://github.com/tmhedberg/SimpylFold .

**Comment by roachsinai** [comment]
> For Python `foldmethod=indent` is a simple popular choice, or try [tmhedberg/SimpylFold](https://github.com/tmhedberg/SimpylFold) .

Thank you so much.
