### ISSUE TITLE
zuz: 'expr' folds already continuously updated

### ISSUE THREAD

**Issue by ossie-git** [Konfekt/FastFold#63]
Hi,

New FastFold user. I installed the plugin using Vundle but it doesn't seem to be running. Whenever I run **zuz**, it gives me:

```
'expr' folds already continuously updated
```

and I can see high CPU usage while typing a new header / fold start, indicating that FastFold isn't kicking in. Any idea on where to start troubleshooting? Thanks

**Comment by Konfekt** [comment]
This is due to a buffer with < 200 lines and the standard setting [`g:fastfold_minlines = 200`](https://github.com/Konfekt/FastFold#configuration). I just decreased this number to `100`.

**Comment by ossie-git** [comment]
Thanks @Konfekt
