### ISSUE TITLE
[bug] conflict with vim-which-key

### ISSUE THREAD

**Issue by Freed-Wu** [Konfekt/FastFold#67]
```vim
" $ uname -r
" 5.13.8-arch1-1
" $ has nvim
" ✓ nvim 0.5.0
" $ has python
" ✓ python 3.9.6
" $ vi test.vim
set runtimepath=$VIMRUNTIME,~/.local/share/nvim/repos/github.com/Konfekt/FastFold,~/.local/share/nvim/repos/github.com/liuchengxu/vim-which-key
nnoremap <nowait> z :<C-u>WhichKey 'z'<CR>
" $ vi -u test.vim demo.vim
```

this is demo.vim:
```vim
" Interaction {{{1 "
" UI {{{2 "
" liuchengxu/vim-which-key {{{3 "
" 3}}} liuchengxu/vim-which-key "
" 2}}} UI "

" KeyMap {{{2 "
" lyokha/vim-xkbswitch {{{3 "
" 3}}} lyokha/vim-xkbswitch "
" 2}}} KeyMap "
" 1}}} Interaction "
" ex: foldmethod=marker
```

after `vi -u test.vim demo.vim`
![Screenshot from 2021-08-14 22-30-47](https://user-images.githubusercontent.com/32936898/129449680-e3e4a42e-12a0-4e84-89e9-afdcfd58b859.png)
after `3ggl`, the folder was opened.
![Screenshot from 2021-08-14 22-31-19](https://user-images.githubusercontent.com/32936898/129449693-5f64e11c-b22a-4e01-a1c3-a2e004195326.png)
after `2dd`, a folder was deleted.
![Screenshot from 2021-08-14 22-32-36](https://user-images.githubusercontent.com/32936898/129449717-2fe6719a-5eb1-42e2-8986-de28e37e5cb1.png)

after `z`, wait to the popup window, vim-which-key will give you a popup window to prompt what hotkey has been mapped.
![Screenshot from 2021-08-14 22-32-44](https://user-images.githubusercontent.com/32936898/129449710-f15a538c-2f4d-4ff6-a696-0b58a2e61070.png)
after `j`, it should jump to next folder, however:
![Screenshot from 2021-08-14 22-32-47](https://user-images.githubusercontent.com/32936898/129449725-f78483a3-95fd-40a6-9daf-e4d4bd88925d.png)
some lines were deleted. this is a bug.

thanks.

**Comment by Konfekt** [comment]
This is a bit cryptic, but might it be due to FastFold overriding the fold mappings `z...` by [default](https://github.com/Konfekt/FastFold#configuration) and `vim-which-key` doing something similar?

**Comment by Konfekt** [comment]
That is, does the issue go away with `let g:fastfold_fold_command_suffixes = []` ? After `nmap <Plug>(DisableFFU) <Plug>(FastFoldUpdate)`?

**Comment by Freed-Wu** [comment]
```vim
" $ uname -r
" 5.13.8-arch1-1
" $ has nvim
" ✓ nvim 0.5.0
" $ has python
" ✓ python 3.9.6
" $ vi test.vim
set runtimepath=$VIMRUNTIME,~/.local/share/nvim/repos/github.com/Konfekt/FastFold,~/.local/share/nvim/repos/github.com/liuchengxu/vim-which-key
nnoremap <nowait> z :<C-u>WhichKey 'z'<CR>
let g:fastfold_fold_command_suffixes = []
nmap <Plug>(DisableFFU) <Plug>(FastFoldUpdate)
" $ vi -u test.vim demo.vim
```

The bug still exists.

**Comment by Konfekt** [comment]
I am sorry, the images are hard to read. The issue should go away by removing `'zj', 'zk'` from ` g:fastfold_fold_movement_commands`, that is

```vim
let g:fastfold_fold_movement_commands = [']z', '[z']
```

Still, `vim-which-key` seems to change the mapping in such a way that it deletes lines. I would be glad if they gave some feedback as well.

**Comment by Konfekt** [comment]
@liuchengxu : Might this be due to `zj` being an expression mapping?

**Comment by Freed-Wu** [comment]
> I am sorry, the images are hard to read. The issue should go away by removing `'zj', 'zk'` from ` g:fastfold_fold_movement_commands`, that is
> 
> ```viml
> let g:fastfold_fold_movement_commands = [']z', '[z']
> ```
> 
> Still, `vim-which-key` seems to change the mapping in such a way that it deletes lines. I would be glad if they gave some feedback as well.

Opoos! this bug is not only about zj:
```vim
" $ uname -r
" 5.13.8-arch1-1
" $ has nvim
" ✓ nvim 0.5.0
" $ has python
" ✓ python 3.9.6
" $ vi test.vim
set runtimepath=$VIMRUNTIME,~/.local/share/nvim/repos/github.com/Konfekt/FastFold,~/.local/share/nvim/repos/github.com/liuchengxu/vim-which-key
nnoremap <nowait> [ :<C-u>WhichKey '['<CR>
nnoremap <nowait> ] :<C-u>WhichKey ']'<CR>
let g:fastfold_fold_movement_commands = [']z', '[z']
" $ vi -u test.vim demo.vim
```

Now change zj to ']z', this bug can be reproduced.

**Comment by Konfekt** [comment]
In the meanwhile, you can do without updating folds when moving with `zj/k` and `[/]z` by `let g:fastfold_fold_movement_commands = []`. I think `vim-which-key` makes a tremendous effort to reproduce this expression maps, but somehow fails. Let's wait for @liuchengxu 's comments.

**Comment by liuchengxu** [comment]
First of all, vim-which-key won't change any of the existing key mappings. From the following debugging prints, vim-which-key simply executes the command using `feedkeys()` and I believe this is the expected behavior. So it's probably on Vim or FastFold?

```diff
diff --git a/autoload/which_key.vim b/autoload/which_key.vim
index cb4fc1c..594c8f1 100644
--- a/autoload/which_key.vim
+++ b/autoload/which_key.vim
@@ -327,14 +327,19 @@ function! s:execute(cmd) abort
       return
     endif
     if Cmd =~? '^<Plug>.\+' || Cmd =~? '^<C-W>.\+' || Cmd =~? '^<.\+>$'
+      echom 'Execte 1'
       let Cmd = s:join('call', 'feedkeys("\'.Cmd.'")')
     elseif Cmd =~? '.(*)$' && match(Cmd, '\<call\>') == -1
+      echom 'Execte 2'
       let Cmd = s:join('call', Cmd)
     elseif exists(':'.Cmd)  || Cmd =~# '^:' || Cmd =~? '^call feedkeys(.*)$'
+      echom 'Execte 3'
       let Cmd = Cmd
     else
+      echom 'Execte 4'
       let Cmd = s:join('call', 'feedkeys("'.Cmd.'")')
     endif
+    echom 'Cmd:'.string(Cmd)
     execute Cmd
   catch
     echom v:exception
```

```
Execte 3                                                                                                                                                                                                      
Cmd:'call feedkeys("\<esc>:\<c-u>call \<SNR>21_UpdateWin()\<CR>\"\"d1zj", "nt")'
```

**Comment by Konfekt** [comment]
It seems that in

```vim
" plugin/fastfold.vim (line 178)
exe "nnoremap <silent><expr> " . cmd. " ':<c-u>call <SID>UpdateWin()<CR>'.v:count." . "'".cmd."'"
```

somehow `v:count` was replaced by `\"\"d1`?

**Comment by Freed-Wu** [comment]
I do some experiment and found some interesting things.
```diff
+++ /home/wzy/.local/share/nvim/repos/github.com/liuchengxu/vim-which-key/autoload/which_key/mappings.vim 2021-07-19 14:56:31.323735637 +0800 @@ -116,20 +116,8 @@

     let lhs_at_level = a:map.lhs[a:level]

-   if lhs_at_level ==# 'j'

-      echom 'a'

-      echom a:map.rhs

-   endif if !has_key(a:dict, lhs_at_level)

-      if lhs_at_level ==# 'j'

-          echom 'b'

-          echom a:map.rhs

-      endif
         let a:dict[lhs_at_level] = [cmd, a:map.display]

-    if lhs_at_level ==# 'j'

-        echom 'c'

-        echom a:map.rhs

-    endif

    " spot is taken already, flatten existing submaps elseif type(a:dict\[lhs_at_level\]) == s:TYPE.dict  && g:which_key_flatten
```

Result:

```
a
<esc>:<c-u>call <SNR>153_UpdateWin()<CR>"+d1zj
b
<esc>:<c-u>call <SNR>153_UpdateWin()<CR>"+d1zj
c
<esc>:<c-u>call <SNR>153_UpdateWin()<CR>"+d1zj
a
:<c-u>call <SNR>153_UpdateWin()<CR>0zj
```

If I
```diff
+++ /home/wzy/.local/share/nvim/repos/github.com/Konfekt/FastFold/plugin/fastfold.vim   2021-08-27 21:58:26.951376487 +0800
@@ -177,7 +177,7 @@
 for cmd in g:fastfold_fold_movement_commands
   exe "nnoremap <silent><expr> " . cmd. " ':<c-u>call <SID>UpdateWin()<CR>'.v:count." . "'".cmd."'"
   exe "xnoremap <silent><expr> " . cmd. " ':<c-u>call <SID>UpdateWin()<CR>gv'.v:count." . "'".cmd."'"
-  " exe "onoremap <silent><expr> " . cmd. " '<esc>:<c-u>call <SID>UpdateWin()<CR>' . '\"' . v:register . v:operator . v:count1 . " . "'".cmd."'"
+  exe "onoremap <silent><expr> " . cmd. " '<esc>:<c-u>call <SID>UpdateWin()<CR>' . '\"' . v:register . v:operator . v:count1 . " . "'".cmd."'"
 endfor

 augroup FastFold
```

Result:

```
a
:<c-u>call <SNR>153_UpdateWin()<CR>0zj
b
:<c-u>call <SNR>153_UpdateWin()<CR>0zj
c
:<c-u>call <SNR>153_UpdateWin()<CR>0zj
```

**Comment by Freed-Wu** [comment]
I believe <https://github.com/liuchengxu/vim-which-key/pull/201> can fix this bug.
